### ISSUE TITLE
Single page mode

### ISSUE THREAD

**Issue by est31** [rust-lang-nursery/reference#68] opened 2017-06-05 21:32 UTC
Many sections of the new split up reference don't contain any content at all at the top level, or contain only little text. If you are reading it in full screen, more than half of the screen is whitespace. It would be really nice to have a single page mode, so that you don't have to click all the time, and so that ctrl+f and friends works.

**Comment by steveklabnik** [comment] 2017-06-06 01:03
Click the "print" button in the upper right hand side for a workaround today.

However, this is a duplicate of https://github.com/azerupi/mdBook/issues/301, so closing in favor of that. Thanks!

**Closed by steveklabnik** 2017-06-06 01:03 UTC

**Comment by bluss** [comment] 2017-10-14 10:04
The reference is much more useful if it is a single page.

**Comment by est31** [comment] 2019-07-23 13:22
I've filed a new issue as that one got closed (for confusion with SPAs): https://github.com/rust-lang-nursery/mdBook/issues/988
